import type { JSX } from "solid-js";
import { BackLink } from "./components/BackLink";
import type { RouteName } from "./router";

export interface CopyrightProps {
  onNavigate: (to: RouteName) => void;
}

/**
 * Legal anchor page — what's covered by which license. The `Credits`
 * page handles attribution detail (who made what); this page is the
 * tighter "what governs your use of TYPE" summary.
 */
export function Copyright(props: CopyrightProps): JSX.Element {
  return (
    <main class="stage page page--narrow">
      <header class="page__head">
        <div class="label">copyright</div>
        <h2 class="page__title">License and copyright.</h2>
      </header>

      <section class="page__body">
        <h3>The app</h3>
        <p>
          © 2026{" "}
          <a href="https://lixiaolai.com" target="_blank" rel="noopener">
            xiaolai
          </a>
          . Source code released under the{" "}
          <a
            href="https://github.com/xiaolai/type-review/blob/main/LICENSE"
            target="_blank"
            rel="noopener"
          >
            MIT License
          </a>
          . You're free to use, modify, and redistribute under the terms in the LICENSE file.
        </p>

        <h3>Bundled text</h3>
        <p>
          The corpus shipped under <code>src/io/corpus/data/</code> is a mix:
        </p>
        <ul>
          <li>
            <b>Public domain</b> — works by Mark Twain, Henry David Thoreau, Ralph Waldo Emerson,
            Marcus Aurelius, Herman Melville, and similar authors whose works are out of copyright
            worldwide.
          </li>
          <li>
            <b>Fair use</b> — short quotation snippets from modern authors, used for the
            transformative purpose of typing practice. Each snippet is bounded in length and
            attributed in the corpus entry's <code>license</code> field.
          </li>
          <li>
            <b>Original</b> — code snippets and pseudo-word drills generated by the engine.
          </li>
        </ul>
        <p>
          If you're a rights-holder and want a snippet removed, open an issue on{" "}
          <a href="https://github.com/xiaolai/type-review/issues" target="_blank" rel="noopener">
            GitHub
          </a>{" "}
          and it'll come out of the next release.
        </p>

        <h3>Your text</h3>
        <p>
          Any text you upload to the library or paste into <em>custom text</em> stays on your
          device. The app never uploads it; the author claims no rights to it.
        </p>

        <h3>Third-party assets and dependencies</h3>
        <p>
          See <a href="#/credits">credits</a> for the full attribution of bundled audio, fonts,
          runtime and tooling — each item with its own license.
        </p>
      </section>

      <div class="actions">
        <BackLink from="copyright" onNavigate={props.onNavigate} />
      </div>
    </main>
  );
}
