export interface DetPracticeItem {
  readonly topic: string;
  readonly before: string;
  readonly word: string;
  readonly prefix: string;
  readonly after: string;
  readonly note: string;
}

export const DET_READ_COMPLETE_ITEMS: readonly DetPracticeItem[] = [
  {
    topic: "education",
    before:
      "The admissions office clarified that portfolio evidence may support but cannot replace standard ",
    word: "admission",
    prefix: "admi",
    after: " requirements.",
    note: "admission requirements = 入学要求。注意 admission 作名词修饰 requirements。",
  },
  {
    topic: "education",
    before: "Students who miss the deadline may still qualify if they meet the core ",
    word: "requirements",
    prefix: "requi",
    after: " by June.",
    note: "meet the requirements 是申请语境里的高频搭配。",
  },
  {
    topic: "education",
    before: "The study tracked ",
    word: "cognitive",
    prefix: "cogn",
    after: " development in children who learned two languages at home.",
    note: "cognitive development = 认知发展。空格前后判断需要形容词。",
  },
  {
    topic: "education",
    before: "Early reading habits can shape vocabulary ",
    word: "development",
    prefix: "deve",
    after: " long before formal schooling begins.",
    note: "development 是抽象名词，常接在 vocabulary/cognitive 后面。",
  },
  {
    topic: "education",
    before: "The workshop used in-depth and ",
    word: "interactive",
    prefix: "inte",
    after: " tasks instead of a lecture-only format.",
    note: "interactive study/tasks 强调参与和互动。",
  },
  {
    topic: "education",
    before: "The school revised the ",
    word: "curriculum",
    prefix: "curr",
    after: " to include climate science and data literacy.",
    note: "curriculum = 课程体系，不是单节课 lesson。",
  },
  {
    topic: "education",
    before: "The final ",
    word: "assessment",
    prefix: "asse",
    after: " combined a short essay with a recorded response.",
    note: "assessment = 评估。词尾 -ment 是名词信号。",
  },
  {
    topic: "education",
    before: "The policy offered copyright ",
    word: "accommodation",
    prefix: "accom",
    after: " for teachers using brief excerpts in class.",
    note: "copyright accommodation 指版权许可或合理安排。",
  },
  {
    topic: "law",
    before: "Libraries need an ",
    word: "intellectual",
    prefix: "intel",
    after: " property license before digitizing rare materials.",
    note: "intellectual property = 知识产权。",
  },
  {
    topic: "law",
    before: "Online publishers must respect ",
    word: "copyright",
    prefix: "copy",
    after: " laws even when content is easy to copy.",
    note: "copyright laws = 版权法。",
  },
  {
    topic: "law",
    before: "The museum obtained a digital ",
    word: "license",
    prefix: "lic",
    after: " before posting the archive online.",
    note: "license 在美式英语中常作名词和动词。",
  },
  {
    topic: "economy",
    before: "Public ",
    word: "institutions",
    prefix: "insti",
    after: " often face higher operating costs than private companies.",
    note: "institutions = 机构；注意复数。",
  },
  {
    topic: "economy",
    before: "Small ",
    word: "enterprises",
    prefix: "ente",
    after: " may relocate when rent rises too quickly.",
    note: "enterprises = 企业；businesses 的正式表达。",
  },
  {
    topic: "economy",
    before: "The city hopes that the research park will attract ",
    word: "profitable",
    prefix: "prof",
    after: " ventures.",
    note: "profitable ventures = 盈利企业或项目。",
  },
  {
    topic: "economy",
    before: "Several firms decided to ",
    word: "relocate",
    prefix: "rel",
    after: " after the provincial tax policy changed.",
    note: "relocate = 迁址；动词由 to 后的不定式判断。",
  },
  {
    topic: "economy",
    before: "Scholarships may cover tuition, books, and other reasonable ",
    word: "expenses",
    prefix: "exp",
    after: ".",
    note: "reasonable expenses = 合理花销。",
  },
  {
    topic: "economy",
    before: "Researchers received travel ",
    word: "allowances",
    prefix: "allo",
    after: " for fieldwork in remote villages.",
    note: "travel allowances = 旅行津贴。",
  },
  {
    topic: "technology",
    before: "The new system can ",
    word: "transfer",
    prefix: "tra",
    after: " the data without exposing personal information.",
    note: "transfer the data = 传输数据。",
  },
  {
    topic: "technology",
    before: "Medical students practiced surgery in a ",
    word: "virtual",
    prefix: "vir",
    after: " reality environment.",
    note: "virtual reality = 虚拟现实。",
  },
  {
    topic: "technology",
    before: "A higher screen ",
    word: "resolution",
    prefix: "reso",
    after: " can make diagrams easier to read.",
    note: "screen resolution = 屏幕分辨率。",
  },
  {
    topic: "technology",
    before: "The web ",
    word: "interface",
    prefix: "inte",
    after: " was redesigned for users with limited technical experience.",
    note: "web interface = 网页界面。",
  },
  {
    topic: "technology",
    before: "The team chose ",
    word: "independent",
    prefix: "inde",
    after: " software instead of a hosted service.",
    note: "independent software = 独立软件。",
  },
  {
    topic: "technology",
    before: "Each prototype must satisfy a clear technical ",
    word: "objective",
    prefix: "obje",
    after: " before it is shown to users.",
    note: "technical objective = 技术目标。",
  },
  {
    topic: "technology",
    before: "Engineers must ",
    word: "formulate",
    prefix: "form",
    after: " problems precisely before proposing solutions.",
    note: "formulate problems = 构想或表述问题。",
  },
  {
    topic: "biology",
    before: "The forest provides a natural ",
    word: "habitat",
    prefix: "hab",
    after: " for several rare insects.",
    note: "natural habitat = 自然栖息地。",
  },
  {
    topic: "biology",
    before: "These plants are ",
    word: "abundant",
    prefix: "abu",
    after: " in rainforests but rare in dry regions.",
    note: "be abundant in = 在某地大量存在。",
  },
  {
    topic: "biology",
    before: "Walking sticks often hide among ",
    word: "broadleaf",
    prefix: "broa",
    after: " trees.",
    note: "broadleaf trees = 阔叶树。",
  },
  {
    topic: "biology",
    before: "Seeds may enter ",
    word: "dormancy",
    prefix: "dor",
    after: " when the climate becomes unpredictable.",
    note: "dormancy = 休眠状态。",
  },
  {
    topic: "biology",
    before: "The species survives adverse ",
    word: "condition",
    prefix: "cond",
    after: " by slowing its growth.",
    note: "adverse condition = 不利条件。注意这里需要单数名词。",
  },
  {
    topic: "biology",
    before: "A high ",
    word: "mortality",
    prefix: "mort",
    after: " rate can threaten small animal populations.",
    note: "mortality rate = 死亡率。",
  },
  {
    topic: "biology",
    before: "A ",
    word: "tortoise",
    prefix: "tor",
    after: " has a hard shell and slow, deliberate movements.",
    note: "tortoise = 陆龟；不要和 turtle 混淆。",
  },
  {
    topic: "biology",
    before: "Nurse sharks use their ",
    word: "pectoral",
    prefix: "pec",
    after: " fins to rest near the sea floor.",
    note: "pectoral fins = 胸鳍。",
  },
  {
    topic: "biology",
    before: "The delay is a ",
    word: "consequential",
    prefix: "conse",
    after: " response to harsh environmental pressure.",
    note: "consequential = 作为结果产生的；形容词修饰 response。",
  },
  {
    topic: "politics",
    before: "The lecture examined major ",
    word: "constitutional",
    prefix: "const",
    after: " developments in the nineteenth century.",
    note: "constitutional developments = 宪法发展。",
  },
  {
    topic: "politics",
    before: "Parliament's ",
    word: "lawmaking",
    prefix: "lawm",
    after: " functions changed after the reform.",
    note: "lawmaking functions = 立法职能。",
  },
  {
    topic: "politics",
    before: "The purpose of ",
    word: "propaganda",
    prefix: "prop",
    after: " is often to simplify complex political choices.",
    note: "propaganda = 政治宣传。",
  },
  {
    topic: "politics",
    before: "False reports can ",
    word: "infiltrate",
    prefix: "infi",
    after: " public debate during an election.",
    note: "infiltrate = 渗透。这里由 can 后面判断动词原形。",
  },
  {
    topic: "politics",
    before: "Activists urged consumers to ",
    word: "boycott",
    prefix: "boy",
    after: " companies linked to the policy.",
    note: "boycott = 抵制；动词或名词都常见。",
  },
  {
    topic: "politics",
    before: "The prime minister lost his ",
    word: "parliamentary",
    prefix: "parli",
    after: " majority after the vote.",
    note: "parliamentary majority = 议会多数席位。",
  },
  {
    topic: "politics",
    before: "A narrow ",
    word: "majority",
    prefix: "maj",
    after: " supported the bill.",
    note: "majority = 多数；常与 narrow/large 搭配。",
  },
  {
    topic: "politics",
    before: "Several anti-communist ",
    word: "factions",
    prefix: "fac",
    after: " formed a temporary alliance.",
    note: "factions = 派别；注意复数。",
  },
  {
    topic: "politics",
    before: "The law targeted ",
    word: "subversive",
    prefix: "subv",
    after: " persons accused of threatening state security.",
    note: "subversive persons = 颠覆分子。",
  },
  {
    topic: "politics",
    before: "The agency said the files involved state ",
    word: "security",
    prefix: "sec",
    after: ", not ordinary political disagreement.",
    note: "state security = 国土安全或国家安全。",
  },
  {
    topic: "society",
    before: "Many reforms fail because they challenge the ",
    word: "status",
    prefix: "sta",
    after: " quo too directly.",
    note: "the status quo = 现状。",
  },
  {
    topic: "society",
    before: "Opponents tried to ",
    word: "thwart",
    prefix: "thw",
    after: " the proposal before it reached a final vote.",
    note: "thwart = 阻挠。to 后面需要动词原形。",
  },
  {
    topic: "technology",
    before: "Technological ",
    word: "determinism",
    prefix: "dete",
    after: " assumes that tools strongly shape social behavior.",
    note: "technological determinism = 科技决定论。",
  },
  {
    topic: "technology",
    before: "The attackers demanded a ",
    word: "ransom",
    prefix: "ran",
    after: " after locking the company's files.",
    note: "pay/demand a ransom = 交付或索要赎金。",
  },
  {
    topic: "technology",
    before: "A downed router can leave users with ",
    word: "restricted",
    prefix: "rest",
    after: " service for several hours.",
    note: "restricted service = 受限服务。过去分词作形容词。",
  },
  {
    topic: "technology",
    before: "If the server is overloaded, the service may become ",
    word: "unavailable",
    prefix: "unav",
    after: " to remote users.",
    note: "unavailable = 不可用；un- 是否定前缀。",
  },
  {
    topic: "design",
    before: "A product can be technical and still ",
    word: "visually",
    prefix: "vis",
    after: " appealing.",
    note: "visually appealing = 视觉上有吸引力。",
  },
];
